name: Playground
on:
  push: ~

jobs:
  commit_message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get commit message
        run: echo ::set-env name=COMMIT_MESSAGE::$(git log -1 --pretty=format:"%s")

      - name: show commit message
        run: echo $COMMIT_MESSAGE
