name: Test

on:
  - push

jobs:
  git-diff-changed-files:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Create report file
        run: date +%s > report.txt

      -
        name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "Im here"
