name: Test

on:
  - push

jobs:
  rector-ci:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2

      -
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
          coverage: none

      - run: echo $MY_ENV

      - run: php set-env.php

      - run: echo $MY_ENV